name: Deploy s3 to host
on:
  workflow_dispatch:

jobs:
  deploy-to-host:
    name: Deploy s3 to host
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH command
        run: |
          mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config &&
          ssh syryx@51.250.64.209 'docker stop minio_service && docker rm minio_service 2> /dev/null ; 
          docker run --rm --name minio_service -v /home/syryx/minio_storage:/data -d -p 9000:9000 -p 9001:9001 minio/minio server /data --console-address ":9001"'
